from selenium.webdriver.common.by import By

class Locator:
    HEADER_LOGIN_AND_REGISTRATION = By.XPATH, ".//div[contains(@class,'header_')]/button[text()='Вход и регистрация']"
    HEADER_CREATE_AD = By.XPATH, ".//div[contains(@class,'header_')]/button[text()='Разместить объявление']"
    BUTTON_LOGIN = By.XPATH, "//button[text()='Войти']"
    MODAL_WINDOW_AD_CREATE_NOT_AUTHORIZED_USER = By.XPATH, ".//h1[@class='h1']"
    POP_BUTTON_NO_ACCOUNT = By.XPATH, ".//div[contains(@class,'popUp_button')]//button[text()='Нет аккаунта']"
    POP_INPUTS = By.XPATH, ".//div[@class='popUp_inputColumn__RgD8n']//input"
    INPUT_EMAIL = By.NAME, "email"
    INPUT_PASSWORD = By.NAME, "password"
    INPUT_SUBMIT_PASSWORD = By.NAME, "submitPassword"
    POP_BUTTON_CREATE_ACCOUNT = By.XPATH,".//div[contains(@class , 'popUp_')]/button[text() = 'Создать аккаунт']"
    HEADER_AVATAR = By.CLASS_NAME, "svgSmall"
    COLUM_PROFILE_TEXT_NAME = By.XPATH, ".//h3[@class = 'profileText name']"
    COLUM_PROFILE_EXIT = By.XPATH, "//button[@class = 'spanGlobal btnSmall']"
    ERROR_MESSAGE_REGISTRATION_NOT_VALUE_EMAIL = By.XPATH, ".//span[text() = 'Ошибка']"
    FRAME_INPUT_ERROR = By.XPATH, ".//div[@class='popUp_inputColumn__RgD8n']//div[@class='input_inputError__fLUP9']"
    DROPDOWN_BUTTONS = By.CLASS_NAME, "dropDownMenu_arrowDown__pfGL1"
    BUTTON_PUBLISH_AD = By.XPATH, ".//button[text()='Опубликовать']"
    CREATE_DROPDOWN_CITY_ARROW = By.XPATH, ".//input[@name='city']/following-sibling::button[contains(@class,'arrow')]"
    CREATE_DROPDOWN_CITY_BUTTONS = By.XPATH, ".//input[@name='city']/ancestor::div[contains(@class, 'dropDownMenu_dropMenu')]//button[contains(@class, 'dropDownMenu_btn')]"
    CREATE_INPUT_NAME = By.XPATH, ".//div[@class='createListingPage_createListingPageStyle__U-MJJ']//input[@name='name']"
    CREATE_INPUT_PRICE = By.XPATH, ".//div[@class='createListingPage_createListingPageStyle__U-MJJ']//input[@name='price']"
    CREATE_TEXTAREA_DESCRIPTION = By.XPATH, ".//div[@class='createListingPage_createListingPageStyle__U-MJJ']//textarea[@name='description']"
    CREATE_DROPDOWN_CATEGORY_ARROW = By.XPATH, ".//div[@class='dropDownMenu_dropMenu__sBxhz']//input[@name='category']/..//button[contains(@class,'dropDownMenu_arrow')]"
    CREATE_DROPDOWN_CATEGORY_BUTTONS = By.XPATH, "//input[@name='category']/ancestor::div[contains(@class, 'dropDownMenu_dropMenu')]//button[contains(@class, 'dropDownMenu_btn')]"
    CREATE_FIELDSET_CONDITIONS_ACTIVE = By.XPATH, ".//fieldset[contains(@class, 'createListing_inputRadio')]//div[@class='radioUnput_inputActive__eC-HY']"
    CREATE_FIELDSET_CONDITIONS_REGULAR = By.XPATH, ".//fieldset[contains(@class, 'createListing_inputRadio')]//div[@class='radioUnput_inputRegular__FbVbr']"
    CREATE_BUTTON_PUBLISH = By.XPATH, ".//button[@type='submit' and text()='Опубликовать']"
    HEADER_USER_AVATAR = By.XPATH, ".//div[contains(@class,'header_')]//button[@class='circleSmall']"
    PROFILE_CARD_BUTTON_NEXT_ACTIVE = By.XPATH, ".//button[@class='arrowButton arrowButton--right undefined' and not(@disabled)]"
    PROFILE_CARD_BUTTON_NEXT = By.XPATH, ".//button[@class='arrowButton arrowButton--right undefined']"
    PROFILE_CARD_DESCRIPTION_LAST = By.XPATH, "(.//div[@class='card']/div[@class='description'])[last()]"
    PROFILE_CARD_NAME = By.XPATH, "(//div[@class='about']/h2)[last()]"
    PROFILE_CARD_CITY = By.XPATH, "(//div[@class='about']/h3)[last()]"
    PROFILE_CARD_PRICE = By.XPATH, "(//div[@class='price']/h2)[last()]"
    HOMEPAGE = By.XPATH, ".//div[contains(@class, 'homePage_homepageStyle')]"
